on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure Github
        run: |
          git config --global user.name '@imagistlondon'
          git config --global user.email 'imagistlondon@users.noreply.github.com'

      - name: Install Flutter
        run: |
          cd app
          git clone --depth 1 --branch 1.26.0-17.6.pre https://github.com/flutter/flutter.git
          ./flutter/bin/flutter --version
          ./flutter/bin/flutter config --enable-web
          ls -la

      - name: Build Release
        run: |
          cd app
          ./flutter/bin/flutter build web --release
          ls -la

      - name: Delete docs/*
        run: |
          cd docs
          rm -rf *

      - name: Copy app/build/web/* to docs/*
        run: cp -a app/build/web/. docs/

      - name: Commit docs/*
        run: |
          git add docs/*
          git commit -m "docs"
          git push