on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
          channel: 'stable'

      - name: Configure Github
        run: |
          git config --global user.name '@imagistlondon'
          git config --global user.email 'imagistlondon@users.noreply.github.com'

      - name: Build Release
        run: |
          cd app
          ./flutter/bin/flutter build web --web-renderer canvaskit --release --source-maps
          ls -la

      - name: Delete docs/*
        run: |
          cd docs
          rm -rf *

      - name: Copy app/build/web/* to docs/*
        run: cp -a app/build/web/. docs/

      - name: Commit docs/*
        run: |
          git add docs/*
          git commit -m "docs"
          git push