on:
  push:
    branches:
      - master

jobs:

  # Builds and publishes artifact (using gradle)
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create report file
        run: date +%s > report.txt

      - name: Commit report
        run: |
          git commit -am "Automated report"
          git push

      - name: Install Flutter
        run: |
          cd app
          git clone -b master https://github.com/flutter/flutter.git
          ./flutter/bin/flutter --version
          ./flutter/bin/flutter config --enable-web
          ls -la

      - name: Build Release
        run: |
          cd app
          ./flutter/bin/flutter build web --release
          ls -la

      - run: ls -la