on:
  push:
    branches:
      - master

jobs:

  # Builds and publishes artifact (using gradle)
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure Github
        run: |
          git config --global user.name '@imagistlondon'
          git config --global user.email 'imagistlondon@users.noreply.github.com'

      - name: Install Flutter
        run: |
          cd app
          git clone -b master https://github.com/flutter/flutter.git
          ./flutter/bin/flutter --version
          ./flutter/bin/flutter config --enable-web
          ls -la

      - name: Build Release
        run: |
          cd app
          ./flutter/bin/flutter build web --release
          ls -la

      - name: Delete /docs/*
        run: |
          cd docs
          rm -rf *

      - name: Copy /docs
        run: cp app/build/web /docs

      - name: Commit /docs
        run: |
          git add docs/*
          git commit -m "docs"
          git push